/**
 * Actions associated with practitioner evaluation
 */

 /******* Synchronous actions *********/
export const STORE_QUESTIONS = 'STORE_QUESTION';
export const STORE_QUESTION_CHOICES = 'STORE_QUESTION_CHOICES';
export const STORE_QUESTION_GROUPS = 'STORE_QUESTION_GROUPS';
export const STORE_ALL_RECOMMENDATION_ACTIONS = 'STORE_ALL_RECOMMENDATION_ACTIONS';
export const SAVE_USER_RATING_ACTION = 'SAVE_USER_RATING_ACTION';
export const CLEAR_ALL_RATINGS = 'CLEAR_ALL_RATINGS';
export const STORE_RATING_ACTION_IDS = 'STORE_RATING_ACTION_IDS';

